[package]
name = "r2d2_mysql_batis_macros"
version = "0.1.0"
edition = "2021"
description = "r2d2_mysql_batis_macros"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits"] }